services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    # Veritabanının gerçekten hazır olup olmadığını kontrol eder
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8006
    volumes:
      - .:/django_app
    ports:
      - "8006:8006"
    depends_on:
      db:
        condition: service_healthy # db sağlıklı olana kadar bekle